version: "3"

services: 
  api:
    container_name: signup-manager-api-container
    build: .
    image: signup-manager-api
    restart: always
    command: yarn debugs
    volumes:
      - ./dist:/usr/src/signup-manager-api/dist
      - ./package.json:/usr/src/signup-manager-api/package.json
    ports:
      - "5353:5353"
      - "9222:9222"